imports:
    - { resource: config.yml }

framework:
    router:
        strict_requirements: false

twig:
    debug:                    false
    strict_variables:         false

assetic:
    debug:                    false

doctrine:
    orm:
        auto_generate_proxy_classes: false

parameters:
    performance.customers: 100
    performance.products: 200