classes:
  - Oro\Bundle\SearchBundle\Controller\Api\SoapController
  - Oro\Bundle\UserBundle\Controller\Api\Soap\ProfileController
  - Oro\Bundle\UserBundle\Controller\Api\Soap\RoleController
  - Oro\Bundle\UserBundle\Controller\Api\Soap\GroupController
  - Oro\Bundle\UserBundle\Controller\Api\Soap\AclController
  - Oro\Bundle\AddressBundle\Controller\Api\Soap\AddressController
  - Oro\Bundle\AddressBundle\Controller\Api\Soap\CountryController
  - Oro\Bundle\AddressBundle\Controller\Api\Soap\RegionController
  - Oro\Bundle\DataAuditBundle\Controller\Api\Soap\AuditController
